In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

path = Path("./build_model.ipynb")
abs_path = str(path.parent.absolute())
index = [i for i, e in enumerate(abs_path) if e == "\\"]      
parent_path = abs_path[:index[-2]]
file_path = parent_path + "/data/raw/IPEDS_data.xlsx"
feature_path = parent_path + "/data/raw/columns.txt"

In [2]:
with open(feature_path) as file:
    data =  file.readlines()
    
f = [e.strip() for e in data]
f[4]
print(f[4])

Applicants total

## Exploratory Data Analysis

In [3]:
df = pd.read_excel(file_path, sheet_name=0).loc[:,f]
df.head()

,ID number,Name,Religious affiliation,Offers Bachelor's degree,Applicants total,Admissions total,Enrolled total,Percent of freshmen submitting ACT scores,ACT Composite 25th percentile score,ACT Composite 75th percentile score,...,Number of first-time undergraduates - foreign countries,Percent of first-time undergraduates - foreign countries,"Graduation rate - Bachelor degree within 4 years, total","Graduation rate - Bachelor degree within 5 years, total","Graduation rate - Bachelor degree within 6 years, total",Percent of freshmen receiving any financial aid,"Tuition and fees, 2010-11","Tuition and fees, 2011-12","Tuition and fees, 2012-13","Tuition and fees, 2013-14"
0,100654,Alabama A & M University,Not applicable,Yes,6142.0,5521.0,1104.0,88.0,15.0,19.0,...,NaN,NaN,10.0,23.0,29.0,97.0,5800.0,6828.0,7182.0,7182.0
1,100663,University of Alabama at Birmingham,Not applicable,Yes,5689.0,4934.0,1773.0,93.0,22.0,28.0,...,19.0,1.0,29.0,46.0,53.0,90.0,5806.0,6264.0,6798.0,7206.0
2,100690,Amridge University,Churches of Christ,Yes,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0,0.0,67.0,100.0,8360.0,8720.0,6800.0,6870.0
3,100706,University of Alabama in Huntsville,Not applicable,Yes,2054.0,1656.0,651.0,94.0,23.0,29.0,...,27.0,4.0,16.0,37.0,48.0,87.0,7492.0,8094.0,8794.0,9192.0
4,100724,Alabama State University,Not applicable,Yes,10245.0,5251.0,1479.0,87.0,15.0,19.0,...,67.0,4.0,9.0,19.0,25.0,93.0,7164.0,8082.0,7932.0,8720.0

In [4]:
# check if there are any missing values in the data frame
df.isnull().sum()

ID number                                                                                0
Name                                                                                     0
Religious affiliation                                                                    2
Offers Bachelor's degree                                                                 2
Applicants total                                                                       157
Admissions total                                                                       157
Enrolled total                                                                         157
Percent of freshmen submitting ACT scores                                              275
ACT Composite 25th percentile score                                                    335
ACT Composite 75th percentile score                                                    335
Estimated freshman enrollment, full time                                                19
Number of students receiving a Bachelor's degree                                         2
Percent admitted - total                                                               158
Admissions yield - total                                                               158
Full-time undergraduate enrollment                                                       2
Percent of undergraduate enrollment that are Asian                                      12
Percent of undergraduate enrollment that are White                                      12
Percent of undergraduate enrollment that are Nonresident Alien                          12
Percent of undergraduate enrollment that are Asian/Native Hawaiian/Pacific Islander     12
Number of first-time undergraduates - in-state                                         623
Percent of first-time undergraduates - in-state                                        623
Number of first-time undergraduates - out-of-state                                     623
Percent of first-time undergraduates - out-of-state                                    623
Number of first-time undergraduates - foreign countries                                623
Percent of first-time undergraduates - foreign countries                               623
Graduation rate - Bachelor degree within 4 years, total                                 58
Graduation rate - Bachelor degree within 5 years, total                                 58
Graduation rate - Bachelor degree within 6 years, total                                 58
Percent of freshmen receiving any financial aid                                         42
Tuition and fees, 2010-11                                                               44
Tuition and fees, 2011-12                                                               44
Tuition and fees, 2012-13                                                               42
Tuition and fees, 2013-14                                                               37
dtype: int64

In [5]:
# Check the unique values of all the columns
# df.apply(lambda x: x.unique(), axis=0)
df["Religious affiliation"].unique()

array(['Not applicable', 'Churches of Christ', 'United Methodist',
       'Lutheran Church - Missouri Synod', 'Baptist',
       'Christian Methodist Episcopal', 'Southern Baptist',
       'Seventh Day Adventists', 'Roman Catholic',
       'Presbyterian Church (USA)', 'United Church of Christ',
       'Assemblies of God Church', 'American Baptist', 'Undenominational',
       'Evangelical Lutheran Church',
       'Christian Church (Disciples of Christ)',
       'Mennonite Brethren Church', 'Jewish', 'Interdenominational',
       'Christian Churches and Churches of Christ',
       'Church of the Nazarene', 'Christ and Missionary Alliance Church',
       'African Methodist Episcopal',
       'Evangelical Free Church of America', 'Church of God',
       'The Presbyterian Church in America',
       'Pentecostal Holiness Church', nan,
       'Latter Day Saints (Mormon Church)', 'Free Methodist',
       'Evangelical Covenant Church of America', 'Missionary Church Inc',
       'Friends', 'Mennonite Church', 'Brethren Church',
       'United Brethren Church', 'Church of Brethren', 'Wesleyan',
       'Lutheran Church in America', 'Reformed Church in America',
       'Christian Reformed Church', 'Other (none of the above)',
       'Other Protestant', 'Wisconsin Evangelical Lutheran Synod',
       'African Methodist Episcopal Zion Church',
       'Original Free Will Baptist', 'Protestant Episcopal',
       'Moravian Church', 'Reformed Presbyterian Church',
       'Cumberland Presbyterian', 'Free Will Baptist Church',
       'Multiple Protestant Denomination',
       'American Evangelical Lutheran Church', 'Evangelical Christian',
       'Presbyterian'], dtype=object)

In [15]:
# Check the data type of all the variables
df.dtypes

ID number                                                                                int64
Name                                                                                    object
Religious affiliation                                                                   object
Offers Bachelor's degree                                                                object
Applicants total                                                                       float64
Admissions total                                                                       float64
Enrolled total                                                                         float64
Percent of freshmen submitting ACT scores                                              float64
ACT Composite 25th percentile score                                                    float64
ACT Composite 75th percentile score                                                    float64
Estimated freshman enrollment, full time                                               float64
Number of students receiving a Bachelor's degree                                       float64
Percent admitted - total                                                               float64
Admissions yield - total                                                               float64
Full-time undergraduate enrollment                                                     float64
Percent of undergraduate enrollment that are Asian                                     float64
Percent of undergraduate enrollment that are White                                     float64
Percent of undergraduate enrollment that are Nonresident Alien                         float64
Percent of undergraduate enrollment that are Asian/Native Hawaiian/Pacific Islander    float64
Number of first-time undergraduates - in-state                                         float64
Percent of first-time undergraduates - in-state                                        float64
Number of first-time undergraduates - out-of-state                                     float64
Percent of first-time undergraduates - out-of-state                                    float64
Number of first-time undergraduates - foreign countries                                float64
Percent of first-time undergraduates - foreign countries                               float64
Graduation rate - Bachelor degree within 4 years, total                                float64
Graduation rate - Bachelor degree within 5 years, total                                float64
Graduation rate - Bachelor degree within 6 years, total                                float64
Percent of freshmen receiving any financial aid                                        float64
Tuition and fees, 2010-11                                                              float64
Tuition and fees, 2011-12                                                              float64
Tuition and fees, 2012-13                                                              float64
Tuition and fees, 2013-14                                                              float64
dtype: object

In [7]:
# tmp = df.iloc[2,:]
# tmp

## Data Preprocessing

In [8]:
df_notna = df.loc[df["Number of first-time undergraduates - in-state"].notna()]
df_notna.isnull().sum()

ID number                                                                                0
Name                                                                                     0
Religious affiliation                                                                    0
Offers Bachelor's degree                                                                 0
Applicants total                                                                        52
Admissions total                                                                        52
Enrolled total                                                                          52
Percent of freshmen submitting ACT scores                                              107
ACT Composite 25th percentile score                                                    152
ACT Composite 75th percentile score                                                    152
Estimated freshman enrollment, full time                                                 0
Number of students receiving a Bachelor's degree                                         0
Percent admitted - total                                                                52
Admissions yield - total                                                                52
Full-time undergraduate enrollment                                                       0
Percent of undergraduate enrollment that are Asian                                       0
Percent of undergraduate enrollment that are White                                       0
Percent of undergraduate enrollment that are Nonresident Alien                           0
Percent of undergraduate enrollment that are Asian/Native Hawaiian/Pacific Islander      0
Number of first-time undergraduates - in-state                                           0
Percent of first-time undergraduates - in-state                                          0
Number of first-time undergraduates - out-of-state                                       0
Percent of first-time undergraduates - out-of-state                                      0
Number of first-time undergraduates - foreign countries                                  0
Percent of first-time undergraduates - foreign countries                                 0
Graduation rate - Bachelor degree within 4 years, total                                  9
Graduation rate - Bachelor degree within 5 years, total                                  9
Graduation rate - Bachelor degree within 6 years, total                                  9
Percent of freshmen receiving any financial aid                                          3
Tuition and fees, 2010-11                                                                3
Tuition and fees, 2011-12                                                                3
Tuition and fees, 2012-13                                                                3
Tuition and fees, 2013-14                                                                1
dtype: int64

In [9]:
df_notna = df_notna.loc[df["ACT Composite 25th percentile score"].notna()]
df_notna.isnull().sum()

ID number                                                                              0
Name                                                                                   0
Religious affiliation                                                                  0
Offers Bachelor's degree                                                               0
Applicants total                                                                       0
Admissions total                                                                       0
Enrolled total                                                                         0
Percent of freshmen submitting ACT scores                                              0
ACT Composite 25th percentile score                                                    0
ACT Composite 75th percentile score                                                    0
Estimated freshman enrollment, full time                                               0
Number of students receiving a Bachelor's degree                                       0
Percent admitted - total                                                               0
Admissions yield - total                                                               0
Full-time undergraduate enrollment                                                     0
Percent of undergraduate enrollment that are Asian                                     0
Percent of undergraduate enrollment that are White                                     0
Percent of undergraduate enrollment that are Nonresident Alien                         0
Percent of undergraduate enrollment that are Asian/Native Hawaiian/Pacific Islander    0
Number of first-time undergraduates - in-state                                         0
Percent of first-time undergraduates - in-state                                        0
Number of first-time undergraduates - out-of-state                                     0
Percent of first-time undergraduates - out-of-state                                    0
Number of first-time undergraduates - foreign countries                                0
Percent of first-time undergraduates - foreign countries                               0
Graduation rate - Bachelor degree within 4 years, total                                2
Graduation rate - Bachelor degree within 5 years, total                                2
Graduation rate - Bachelor degree within 6 years, total                                2
Percent of freshmen receiving any financial aid                                        2
Tuition and fees, 2010-11                                                              1
Tuition and fees, 2011-12                                                              1
Tuition and fees, 2012-13                                                              1
Tuition and fees, 2013-14                                                              0
dtype: int64

In [10]:
df_notna = df_notna.loc[df["Graduation rate - Bachelor degree within 4 years, total"].notna()]
df_notna.isnull().sum()

ID number                                                                              0
Name                                                                                   0
Religious affiliation                                                                  0
Offers Bachelor's degree                                                               0
Applicants total                                                                       0
Admissions total                                                                       0
Enrolled total                                                                         0
Percent of freshmen submitting ACT scores                                              0
ACT Composite 25th percentile score                                                    0
ACT Composite 75th percentile score                                                    0
Estimated freshman enrollment, full time                                               0
Number of students receiving a Bachelor's degree                                       0
Percent admitted - total                                                               0
Admissions yield - total                                                               0
Full-time undergraduate enrollment                                                     0
Percent of undergraduate enrollment that are Asian                                     0
Percent of undergraduate enrollment that are White                                     0
Percent of undergraduate enrollment that are Nonresident Alien                         0
Percent of undergraduate enrollment that are Asian/Native Hawaiian/Pacific Islander    0
Number of first-time undergraduates - in-state                                         0
Percent of first-time undergraduates - in-state                                        0
Number of first-time undergraduates - out-of-state                                     0
Percent of first-time undergraduates - out-of-state                                    0
Number of first-time undergraduates - foreign countries                                0
Percent of first-time undergraduates - foreign countries                               0
Graduation rate - Bachelor degree within 4 years, total                                0
Graduation rate - Bachelor degree within 5 years, total                                0
Graduation rate - Bachelor degree within 6 years, total                                0
Percent of freshmen receiving any financial aid                                        1
Tuition and fees, 2010-11                                                              0
Tuition and fees, 2011-12                                                              0
Tuition and fees, 2012-13                                                              0
Tuition and fees, 2013-14                                                              0
dtype: int64

In [11]:
df_notna = df_notna.loc[df["Percent of freshmen receiving any financial aid"].notna()]
df_notna.isnull().sum()

ID number                                                                              0
Name                                                                                   0
Religious affiliation                                                                  0
Offers Bachelor's degree                                                               0
Applicants total                                                                       0
Admissions total                                                                       0
Enrolled total                                                                         0
Percent of freshmen submitting ACT scores                                              0
ACT Composite 25th percentile score                                                    0
ACT Composite 75th percentile score                                                    0
Estimated freshman enrollment, full time                                               0
Number of students receiving a Bachelor's degree                                       0
Percent admitted - total                                                               0
Admissions yield - total                                                               0
Full-time undergraduate enrollment                                                     0
Percent of undergraduate enrollment that are Asian                                     0
Percent of undergraduate enrollment that are White                                     0
Percent of undergraduate enrollment that are Nonresident Alien                         0
Percent of undergraduate enrollment that are Asian/Native Hawaiian/Pacific Islander    0
Number of first-time undergraduates - in-state                                         0
Percent of first-time undergraduates - in-state                                        0
Number of first-time undergraduates - out-of-state                                     0
Percent of first-time undergraduates - out-of-state                                    0
Number of first-time undergraduates - foreign countries                                0
Percent of first-time undergraduates - foreign countries                               0
Graduation rate - Bachelor degree within 4 years, total                                0
Graduation rate - Bachelor degree within 5 years, total                                0
Graduation rate - Bachelor degree within 6 years, total                                0
Percent of freshmen receiving any financial aid                                        0
Tuition and fees, 2010-11                                                              0
Tuition and fees, 2011-12                                                              0
Tuition and fees, 2012-13                                                              0
Tuition and fees, 2013-14                                                              0
dtype: int64

In [12]:
print(df_notna.shape)
print(df.shape)

(756, 33)
(1534, 33)

In [13]:
df_notna.head()

,ID number,Name,Religious affiliation,Offers Bachelor's degree,Applicants total,Admissions total,Enrolled total,Percent of freshmen submitting ACT scores,ACT Composite 25th percentile score,ACT Composite 75th percentile score,...,Number of first-time undergraduates - foreign countries,Percent of first-time undergraduates - foreign countries,"Graduation rate - Bachelor degree within 4 years, total","Graduation rate - Bachelor degree within 5 years, total","Graduation rate - Bachelor degree within 6 years, total",Percent of freshmen receiving any financial aid,"Tuition and fees, 2010-11","Tuition and fees, 2011-12","Tuition and fees, 2012-13","Tuition and fees, 2013-14"
1,100663,University of Alabama at Birmingham,Not applicable,Yes,5689.0,4934.0,1773.0,93.0,22.0,28.0,...,19.0,1.0,29.0,46.0,53.0,90.0,5806.0,6264.0,6798.0,7206.0
3,100706,University of Alabama in Huntsville,Not applicable,Yes,2054.0,1656.0,651.0,94.0,23.0,29.0,...,27.0,4.0,16.0,37.0,48.0,87.0,7492.0,8094.0,8794.0,9192.0
4,100724,Alabama State University,Not applicable,Yes,10245.0,5251.0,1479.0,87.0,15.0,19.0,...,67.0,4.0,9.0,19.0,25.0,93.0,7164.0,8082.0,7932.0,8720.0
5,100751,The University of Alabama,Not applicable,Yes,30975.0,17515.0,6454.0,76.0,22.0,30.0,...,162.0,3.0,43.0,62.0,67.0,75.0,7900.0,8600.0,9200.0,9450.0
7,100830,Auburn University at Montgomery,Not applicable,Yes,1958.0,1639.0,579.0,54.0,18.0,23.0,...,0.0,0.0,10.0,22.0,27.0,90.0,6620.0,7580.0,8150.0,8750.0

In [14]:
df_notna.describe().T

,count,mean,std,min,25%,50%,75%,max
ID number,756.0,182960.514550,46242.197746,100663.0,149707.50,184129.0,216100.25,448840.0
Applicants total,756.0,7538.437831,8827.528512,119.0,1999.50,4160.5,9326.50,57845.0
Admissions total,756.0,4294.232804,4677.024618,62.0,1299.75,2519.5,5214.50,35815.0
Enrolled total,756.0,1311.830688,1439.380321,33.0,393.50,729.0,1620.75,10241.0
Percent of freshmen submitting ACT scores,756.0,56.314815,30.467724,1.0,30.00,52.0,89.00,100.0
ACT Composite 25th percentile score,756.0,20.783069,3.498045,13.0,18.00,20.0,22.00,33.0
ACT Composite 75th percentile score,756.0,25.699735,3.370468,16.0,24.00,25.0,28.00,35.0
"Estimated freshman enrollment, full time",756.0,1288.068783,1421.371185,33.0,386.00,697.5,1585.50,9030.0
Number of students receiving a Bachelor's degree,756.0,1411.548942,1675.044716,33.0,352.75,721.0,1727.75,12080.0
Percent admitted - total,756.0,64.525132,18.739855,6.0,54.00,66.0,78.00,100.0
Admissions yield - total,756.0,33.611111,13.904864,8.0,23.00,31.5,41.00,91.0
Full-time undergraduate enrollment,756.0,6076.478836,6896.286481,120.0,1578.50,3192.5,7652.75,40020.0
Percent of undergraduate enrollment that are Asian,756.0,4.187831,5.559709,0.0,1.00,2.0,5.00,42.0
Percent of undergraduate enrollment that are White,756.0,62.515873,21.105375,0.0,54.00,67.5,78.00,96.0
Percent of undergraduate enrollment that are Nonresident Alien,756.0,3.706349,4.082398,0.0,1.00,2.0,5.00,39.0
Percent of undergraduate enrollment that are Asian/Native Hawaiian/Pacific Islander,756.0,4.394180,5.776698,0.0,1.00,2.0,5.00,48.0
Number of first-time undergraduates - in-state,756.0,945.435185,1155.731922,5.0,199.00,451.0,1226.25,9768.0
Percent of first-time undergraduates - in-state,756.0,68.357143,24.456735,1.0,54.00,74.0,88.00,100.0
Number of first-time undergraduates - out-of-state,756.0,320.747354,474.742767,0.0,58.00,136.0,363.75,3704.0
Percent of first-time undergraduates - out-of-state,756.0,27.886243,22.685358,0.0,9.00,22.0,42.00,94.0
Number of first-time undergraduates - foreign countries,756.0,46.469577,110.149437,0.0,3.00,12.0,42.00,1341.0
Percent of first-time undergraduates - foreign countries,756.0,3.130952,4.416111,0.0,1.00,2.0,4.00,40.0
"Graduation rate - Bachelor degree within 4 years, total",756.0,38.206349,21.452977,2.0,21.00,34.5,52.25,93.0
"Graduation rate - Bachelor degree within 5 years, total",756.0,52.082011,18.975373,9.0,38.00,51.0,64.00,96.0
"Graduation rate - Bachelor degree within 6 years, total",756.0,55.734127,17.585875,14.0,43.00,55.0,67.00,98.0
Percent of freshmen receiving any financial aid,756.0,89.775132,11.884420,41.0,85.00,94.0,99.00,100.0
"Tuition and fees, 2010-11",756.0,17409.777778,11704.488143,910.0,6689.00,13496.0,26551.75,43304.0
"Tuition and fees, 2011-12",756.0,18293.563492,12113.832152,910.0,7064.25,13995.0,28026.00,45290.0
"Tuition and fees, 2012-13",756.0,19096.349206,12571.860862,4150.0,7400.25,14615.0,28872.00,47246.0
"Tuition and fees, 2013-14",756.0,19784.190476,13049.845967,4358.0,7570.50,15184.0,29901.00,49138.0

<font size=3>Explanantion for what I did:
1. "columns.txt" is feature selection.
2. Remove all missing values.
3. Remove all row that its percent of freshmen submitting ACT scores is lower than 30.	
    
What I Expect with smaller dataset:
1. Less fit time for models.
2. More attempt for different methods and hyperparameters tunning.

</font>

## Model Creation